services:
  - type: web
    name: canteen-token-generator
    runtime: node
    buildCommand: npm install && npm install --prefix client && npm run build --prefix client
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
